### ISSUE TITLE
Google Login: Library v1.12.1 and later are broken on Android API 21

### ISSUE THREAD

**Issue by ashishb** [googleapis/google-auth-library-java#1215]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-auth-library-java/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: Android API 21
3. Java version: Java 7
4.  version(s): v1.12 is good. v1.12 and later (including v1.17) are broken

#### Stack trace
```
java.lang.NoSuchMethodError: No virtual method getAndSetObject(Ljava/lang/Object;JLjava/lang/Object;)Ljava/lang/Object; in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
   E      at com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper.gasWaiters(AbstractFuture.java:1394)
   E      at com.google.common.util.concurrent.AbstractFuture.releaseWaiters(AbstractFuture.java:1110)
   E      at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1000)
   E      at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
   E      at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.access$400(OAuth2Credentials.java:600)
   E      at com.google.auth.oauth2.OAuth2Credentials$RefreshTask$1.onSuccess(OAuth2Credentials.java:617)
   E      at com.google.auth.oauth2.OAuth2Credentials$RefreshTask$1.onSuccess(OAuth2Credentials.java:614)
   E      at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
   E      at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
   E      at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:143)
   E      at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:132)
   E      at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:111)
   E      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
   E      at java.util.concurrent.FutureTask.set(FutureTask.java:204)
   E      at java.util.concurrent.FutureTask.run(FutureTask.java:245)
   E      at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633)
   E      at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
   E      at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:581)
   E      at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:232)
   E      at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:182)
   E      at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:931)
   E      at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
   E      at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:91)
   E      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:442)
   E      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:552)
   E      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493)
   E      at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603)
```

Ref: https://gist.github.com/ashishb/108a095603446fa39eb901b006642af6

#### External references such as API reference guides

- ?

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by TimurSadykov** [comment]
@ashishb This library supports Java 8+ [starting](https://github.com/googleapis/google-auth-library-java/releases/tag/v1.0.0) version 1.0.0.
