### ISSUE TITLE
OAuth2 over proxy doesn't work.

### ISSUE THREAD

**Issue by bullet-tooth** [googleapis/google-auth-library-java#127]
I'm using [spanner java client](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-spanner) with [gcloud SDK](https://cloud.google.com/sdk/gcloud/) and trying to connect to Google Spanner from machine that uses proxy for internet access.   
I have configured gcloud to use my proxy server and it is ok.
I have specified environment variable GRPC_PROXY_EXP and Spanner requests to **spanner.googleapis.com** go through proxy and it's ok as well.  

 But spanner sql requests fail with `com.google.cloud.spanner.SpannerException: UNAUTHENTICATED` exception because of another error related to OAuth2:
```
Caused by: java.net.UnknownHostException: accounts.google.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
	at com.google.auth.oauth2.UserCredentials.refreshAccessToken(UserCredentials.java:207)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:149)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:135)
	at io.grpc.auth.GoogleAuthLibraryCallCredentials$1.run(GoogleAuthLibraryCallCredentials.java:110)
	... 3 common frames omitted

```
I wend deeper in the code and found that https://github.com/google/google-auth-library-java/blob/0fab63ca9798b78929e52d0313fe54241bda6256/oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java#L64 initializes with default parameters and without any possibility to  configure proxy settings.

If you find it reasonable I would be glad to make PR.

**Comment by lesv** [comment]
In his PR, @bullet-tooth wrote:

OAuth2 Proxy support
-------------------------------
Proxy settings can be configured using `HTTP_PROXY` or `SOCKS_PROXY` environment variables. 
 In case both variables are specified `HTTP_PROXY` will be used.  
 Format: `IP:port`.     
Example: 
 ```shell
 export HTTP_PROXY="123.123.123.123:8080"
 
 #Or with 80 port as default
 export HTTP_PROXY="123.123.123.123" 
```

This is an important FR that we should consider for our Client Libraries.

**Comment by chingor13** [comment]
gRPC and the `NetHttpTransport` handles the standard system proxy properties. If you need to customize the transport further, you can provide your own `HttpTransportFactory` to any credential type or to the [Application Default Credentials](https://googleapis.dev/java/google-auth-library/latest/com/google/auth/oauth2/GoogleCredentials.html#getApplicationDefault-com.google.auth.http.HttpTransportFactory-)
