### ISSUE TITLE
An error getting default credentials on GAE Standard / Java8

### ISSUE THREAD

**Issue by wholegroup** [googleapis/google-auth-library-java#191]
This issue looks similar to  #172. I don't get default credentials manually but use [objectify](https://github.com/objectify/objectify) that calls `DatastoreOptions.getDefaultInstance().getService()`
When I use `google-auth-library-java v0.7.0` getting credentials works well and is broken when i switch to `0.7.1` (or `0.11.0`).

It definitely looks like a bug/regression.

```
com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine: Failed to detect whether we are running on Google Compute Engine. (ComputeEngineCredentials.java:222)
java.io.IOException: 
	at com.google.appengine.api.urlfetch.URLFetchServiceImpl.convertApplicationException(URLFetchServiceImpl.java:185)
	at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:45)
	at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.fetchResponse(URLFetchServiceStreamHandler.java:571)
	at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.getInputStream(URLFetchServiceStreamHandler.java:450)
	at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.getResponseCode(URLFetchServiceStreamHandler.java:303)
	at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:105)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.auth.oauth2.ComputeEngineCredentials.runningOnComputeEngine(ComputeEngineCredentials.java:210)
	at com.google.auth.oauth2.DefaultCredentialsProvider.tryGetComputeCredentials(DefaultCredentialsProvider.java:290)
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentialsUnsynchronized(DefaultCredentialsProvider.java:207)
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:124)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:127)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:100)
	at com.google.cloud.ServiceOptions.defaultCredentials(ServiceOptions.java:304)
	at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:278)
	at com.google.cloud.datastore.DatastoreOptions.<init>(DatastoreOptions.java:102)
	at com.google.cloud.datastore.DatastoreOptions.<init>(DatastoreOptions.java:35)
	at com.google.cloud.datastore.DatastoreOptions$Builder.build(DatastoreOptions.java:89)
	at com.google.cloud.datastore.DatastoreOptions.getDefaultInstance(DatastoreOptions.java:158)
	at com.googlecode.objectify.ObjectifyFactory.<init>(ObjectifyFactory.java:84)
	at com.googlecode.objectify.ObjectifyService.init(ObjectifyService.java:22)
```

**Comment by chingor13** [comment]
Can you post an example code sample for how you've set up objectify to build your Datastore client?

I [modified](https://github.com/chingor13/java-docs-samples/tree/datastore-default-credentials-gae/appengine-java8/datastore) one of the GAE Standard Java 8 samples to ask for default credentials explicitly and to ask for the default Datastore client via `DatastoreOptions.getDefaultInstance().getService()` and neither one runs into this exception.

```bash
mvn dependency:tree
...snip...
[INFO] ------------< com.example.appengine:appengine-datastore-j8 >------------
[INFO] Building appengine-datastore-j8 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ appengine-datastore-j8 ---
[INFO] com.example.appengine:appengine-datastore-j8:war:1.0-SNAPSHOT
[INFO] +- com.google.appengine:appengine-api-1.0-sdk:jar:1.9.64:compile
[INFO] +- javax.servlet:javax.servlet-api:jar:3.1.0:provided
[INFO] +- com.google.auto.value:auto-value:jar:1.5.4:provided
[INFO] +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] +- com.google.guava:guava:jar:25.1-android:compile
[INFO] |  +- org.checkerframework:checker-compat-qual:jar:2.0.0:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO] |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] +- com.google.auth:google-auth-library-oauth2-http:jar:0.11.0:compile
[INFO] |  +- com.google.auth:google-auth-library-credentials:jar:0.11.0:compile
[INFO] |  +- com.google.http-client:google-http-client:jar:1.24.1:compile
[INFO] |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |  |     +- org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[INFO] |  |     +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |     \- commons-codec:commons-codec:jar:1.9:compile
[INFO] |  \- com.google.http-client:google-http-client-jackson2:jar:1.24.1:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.9.2:compile
[INFO] +- com.google.cloud:google-cloud-datastore:jar:1.43.0:compile
[INFO] |  +- com.google.cloud:google-cloud-core:jar:1.43.0:compile
[INFO] |  |  +- com.google.api:api-common:jar:1.7.0:compile
[INFO] |  |  +- com.google.api:gax:jar:1.30.0:compile
[INFO] |  |  |  \- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java-util:jar:3.6.0:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:1.12.0:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.12.0:compile
[INFO] |  +- com.google.cloud:google-cloud-core-http:jar:1.43.0:compile
[INFO] |  |  +- com.google.oauth-client:google-oauth-client:jar:1.24.1:compile
[INFO] |  |  +- com.google.api-client:google-api-client:jar:1.24.1:compile
[INFO] |  |  +- com.google.http-client:google-http-client-appengine:jar:1.24.1:compile
[INFO] |  |  +- com.google.http-client:google-http-client-jackson:jar:1.24.1:compile
[INFO] |  |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO] |  |  +- com.google.api:gax-httpjson:jar:0.47.0:compile
[INFO] |  |  +- io.opencensus:opencensus-api:jar:0.15.0:compile
[INFO] |  |  \- io.opencensus:opencensus-contrib-http-util:jar:0.15.0:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-datastore-v1:jar:0.26.0:compile
[INFO] |  |  \- com.google.protobuf:protobuf-java:jar:3.6.0:compile
[INFO] |  +- com.google.cloud.datastore:datastore-v1-proto-client:jar:1.6.0:compile
[INFO] |  |  \- com.google.http-client:google-http-client-protobuf:jar:1.20.0:compile
[INFO] |  \- io.grpc:grpc-core:jar:1.13.1:compile
[INFO] |     +- io.grpc:grpc-context:jar:1.13.1:compile
[INFO] |     +- com.google.code.gson:gson:jar:2.7:compile
[INFO] |     \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.12.3:compile
[INFO] +- joda-time:joda-time:jar:2.10:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.mockito:mockito-all:jar:1.10.19:test
[INFO] +- com.google.appengine:appengine-testing:jar:1.9.64:test
[INFO] +- com.google.appengine:appengine-api-stubs:jar:1.9.64:test
[INFO] +- com.google.appengine:appengine-tools-sdk:jar:1.9.64:test
[INFO] \- com.google.truth:truth:jar:0.41:test
[INFO]    +- org.checkerframework:checker-qual:jar:2.0.0:test
[INFO]    \- com.googlecode.java-diff-utils:diffutils:jar:1.3.0:test

```

**Comment by wholegroup** [comment]
@chingor13 The error occurs only in production environment. It works well If I run the code locally (I suppose you ran you code locally). I think the issue can occurs because of using [URL Fetch](https://cloud.google.com/appengine/docs/standard/java/issue-requests) that I have to use in my free application.

I made an [example](https://github.com/wholegroup/Seipah4aeme8/blob/master/src/main/java/com/wholegroup/dbtest/TestServlet.java) to see this bug.

The example [throws exception](https://0-11-0-dot-dbtest-dot-yearmovies.appspot.com/) if I try to work with the datastore. Also I can see `com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine: Failed to detect whether we are running on Google Compute Engine. (ComputeEngineCredentials.java:222)` in log console.

The example works [well](https://0-7-0-dot-dbtest-dot-yearmovies.appspot.com/) with `google-auth-library-oauth2-http 0.7.0`

**Comment by chingor13** [comment]
After further review, the metadata server used by the AppEngine Java 8 runtime is not accessibly via urlfetch. While the AppEngineCredentials may work on the Java 8 runtime, many google-cloud-java clients rely on the metadata server to function an may not work. Thus this is working as intended.
