### ISSUE TITLE
runningOnComputeEngine is broken when using Workload identities (GKE)

### ISSUE THREAD

**Issue by freddd** [googleapis/google-auth-library-java#282]
#### Environment details

- OS: GKE, container based OS
- Java version: 11
- google-auth-library-java version(s): We are using 0.12.0 but the issue is in the latest (0.16.1) as well

#### Steps to reproduce

To reproduce using curl:
```
# Start by running a cloud-sdk pod in the GKE cluster that has workload identity enabled
kubectl run -it --generator=run-pod/v1 --image google/cloud-sdk --namespace default workload-identity-test

# When inside the pod, try to verify without header
curl -H 'Accept: application/json' -H "Metadata-Flavor: Not Google" http://169.254.169.254

# Verify that it does work with the header
curl -H 'Accept: application/json' -H "Metadata-Flavor: Google" http://169.254.169.254
```
In other places in the [ComputeEngineCredentials.java](https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L160) the header is added.

When running the sample in [java-docs-samples](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/auth) using
```
mvn exec:java -Dexec.mainClass=com.google.cloud.auth.samples.AuthExample
    -Dexec.args="compute"
```
it works great as it bypasses the check as we are telling it to explicitly use the compute engine credentials. However when running it with:
```
mvn exec:java -Dexec.mainClass=com.google.cloud.auth.samples.AuthExample
```
using the default credentials it does not work. Even though it should resolve that it is running on compute.

#### Stacktrace

```
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
        at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:132) ~[google-auth-library-oauth2-http-0.16.1.jar:na]
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:115) ~[google-auth-library-oauth2-http-0.16.1.jar:na]
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:88) ~[google-auth-library-oauth2-http-0.16.1.jar:na]
        at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:67) ~[gax-1.45.0.jar:1.45.0]
        at org.springframework.cloud.gcp.core.DefaultCredentialsProvider.getCredentials(DefaultCredentialsProvider.java:67) ~[spring-cloud-gcp-core-1.2.0.BUILD-SNAPSHOT.jar:1.2.0.BUILD-SNAPSHOT]
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:140) ~[gax-1.45.0.jar:1.45.0]
        at com.google.cloud.pubsub.v1.stub.GrpcSubscriberStub.create(GrpcSubscriberStub.java:263) ~[google-cloud-pubsub-1.78.0.jar:1.78.0]
        at org.springframework.cloud.gcp.pubsub.support.DefaultSubscriberFactory.createSubscriberStub(DefaultSubscriberFactory.java:275) ~[spring-cloud-gcp-pubsub-1.2.0.BUILD-SNAPSHOT.jar:1.2.0.BUILD-SNAPSHOT]
        ... 60 common frames omitted
```

#### Code snippet

See `Steps to reproduce`

#### External references such as API reference guides used

- https://github.com/googleapis/google-api-dotnet-client/issues/1409, same issue found and fixed in the dotnet client

#### Any additional information below

Following these steps will guarantee the quickest resolution possible.

Workload identity: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

Note that this works fine in GCE but when using the GKE metadata server it fails. See https://github.com/googleapis/google-api-dotnet-client/issues/1409#issuecomment-500543371. We have also verified that it works using `gcloud` inside of the pod with `gcloud pubsub topics list` and `gcloud auth list`.

I verified the fix by just building and replacing version of the lib in the `java-docs-samples` in the pod with the snapshot version containing the fix and both using compute directly and using default credentials works.

I will submit a PR with a fix shortly.

Thanks!

**Comment by mattnworb** [comment]
FWIW, it seems like the GCE metadata server will now honor a header-less request when the legacy endpoints were disabled. I suspect that GCE may have changed something in the behavior to not break any users of this library or others who are using older versions.

```
$ curl -H 'Accept: application/json' -H "Metadata-Flavor: Not Google" http://169.254.169.254
0.1/
computeMetadata/

# this instance has legacy-endpoints diasbled
$ curl -H 'Accept: application/json' -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/attributes/
disable-legacy-endpoints

# accessing v0.1 returns a 404
$ curl -H 'Accept: application/json' -H "Metadata-Flavor: Google" http://169.254.169.254/v0.1/meta-data/
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v0.1/meta-data/</code> was not found on this server.  <ins>That’s all we know.</ins>

```
