### ISSUE TITLE
403 trying to sign provided bytes: The caller does not have permission

### ISSUE THREAD

**Issue by subesingh1981** [googleapis/google-auth-library-java#462]
POM file detail: 	

              <dependency>
			<groupId>com.google.auth</groupId>
			<artifactId>google-auth-library-appengine</artifactId>
		</dependency>
<spring-cloud-gcp>1.2.4.RELEASE</spring-cloud-gcp>

Libs included in jar

Line 27: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-bom/0.21.1/google-auth-library-bom-0.21.1.pom
	Line 27: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-bom/0.21.1/google-auth-library-bom-0.21.1.pom
	Line 27: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-bom/0.21.1/google-auth-library-bom-0.21.1.pom
	Line 28: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-bom/0.21.1/google-auth-library-bom-0.21.1.pom (4.8 kB at 114 kB/s)
	Line 28: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-bom/0.21.1/google-auth-library-bom-0.21.1.pom (4.8 kB at 114 kB/s)
	Line 28: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-bom/0.21.1/google-auth-library-bom-0.21.1.pom (4.8 kB at 114 kB/s)
	Line 643: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.pom
	Line 643: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.pom
	Line 643: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.pom
	Line 643: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.pom
	Line 643: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.pom
	Line 644: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.pom (3.2 kB at 103 kB/s)
	Line 644: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.pom (3.2 kB at 103 kB/s)
	Line 644: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.pom (3.2 kB at 103 kB/s)
	Line 644: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.pom (3.2 kB at 103 kB/s)
	Line 644: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.pom (3.2 kB at 103 kB/s)
	Line 645: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-parent/0.21.1/google-auth-library-parent-0.21.1.pom
	Line 645: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-parent/0.21.1/google-auth-library-parent-0.21.1.pom
	Line 645: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-parent/0.21.1/google-auth-library-parent-0.21.1.pom
	Line 646: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-parent/0.21.1/google-auth-library-parent-0.21.1.pom (15 kB at 387 kB/s)
	Line 646: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-parent/0.21.1/google-auth-library-parent-0.21.1.pom (15 kB at 387 kB/s)
	Line 646: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-parent/0.21.1/google-auth-library-parent-0.21.1.pom (15 kB at 387 kB/s)
	Line 651: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.pom
	Line 651: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.pom
	Line 651: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.pom
	Line 652: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.pom (2.0 kB at 53 kB/s)
	Line 652: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.pom (2.0 kB at 53 kB/s)
	Line 652: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.pom (2.0 kB at 53 kB/s)
	Line 701: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-bom/1.30.5/google-oauth-client-bom-1.30.5.pom
	Line 701: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-bom/1.30.5/google-oauth-client-bom-1.30.5.pom
	Line 701: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-bom/1.30.5/google-oauth-client-bom-1.30.5.pom
	Line 702: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-bom/1.30.5/google-oauth-client-bom-1.30.5.pom (5.4 kB at 187 kB/s)
	Line 702: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-bom/1.30.5/google-oauth-client-bom-1.30.5.pom (5.4 kB at 187 kB/s)
	Line 702: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-bom/1.30.5/google-oauth-client-bom-1.30.5.pom (5.4 kB at 187 kB/s)
	Line 703: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.pom
	Line 703: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.pom
	Line 703: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.pom
	Line 704: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.pom (3.6 kB at 112 kB/s)
	Line 704: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.pom (3.6 kB at 112 kB/s)
	Line 704: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.pom (3.6 kB at 112 kB/s)
	Line 705: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-parent/1.30.5/google-oauth-client-parent-1.30.5.pom
	Line 705: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-parent/1.30.5/google-oauth-client-parent-1.30.5.pom
	Line 705: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-parent/1.30.5/google-oauth-client-parent-1.30.5.pom
	Line 706: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-parent/1.30.5/google-oauth-client-parent-1.30.5.pom (19 kB at 423 kB/s)
	Line 706: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-parent/1.30.5/google-oauth-client-parent-1.30.5.pom (19 kB at 423 kB/s)
	Line 706: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-parent/1.30.5/google-oauth-client-parent-1.30.5.pom (19 kB at 423 kB/s)
	Line 761: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.pom
	Line 761: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.pom
	Line 761: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.pom
	Line 762: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.pom (2.9 kB at 81 kB/s)
	Line 762: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.pom (2.9 kB at 81 kB/s)
	Line 762: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.pom (2.9 kB at 81 kB/s)
	Line 1085: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.jar
	Line 1085: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.jar
	Line 1085: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.jar
	Line 1092: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.jar (67 kB at 24 kB/s)
	Line 1092: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.jar (67 kB at 24 kB/s)
	Line 1092: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client/1.30.5/google-oauth-client-1.30.5.jar (67 kB at 24 kB/s)
	Line 1099: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.jar
	Line 1099: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.jar
	Line 1099: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.jar
	Line 1102: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.jar
	Line 1102: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.jar
	Line 1102: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.jar
	Line 1106: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.jar (6.8 kB at 2.4 kB/s)
	Line 1106: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.jar (6.8 kB at 2.4 kB/s)
	Line 1106: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-appengine/0.21.1/google-auth-library-appengine-0.21.1.jar (6.8 kB at 2.4 kB/s)
	Line 1110: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.jar (5.7 kB at 2.0 kB/s)
	Line 1110: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.jar (5.7 kB at 2.0 kB/s)
	Line 1110: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-credentials/0.21.1/google-auth-library-credentials-0.21.1.jar (5.7 kB at 2.0 kB/s)
	Line 1114: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.jar
	Line 1114: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.jar
	Line 1114: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.jar
	Line 1114: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.jar
	Line 1114: Step #0: [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.jar
	Line 1125: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.jar (115 kB at 40 kB/s)
	Line 1125: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.jar (115 kB at 40 kB/s)
	Line 1125: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.jar (115 kB at 40 kB/s)
	Line 1125: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.jar (115 kB at 40 kB/s)
	Line 1125: Step #0: [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.21.1/google-auth-library-oauth2-http-0.21.1.jar (115 kB at 40 kB/s)

Please include as much information as possible:

#### Environment details

- OS: Debian
- Java version: 11
- google-auth-library-java version(s): 0.21.1

#### Steps to reproduce

1. upload a file in GCS bucket.
2. Try to download it using code given below.

#### Stacktrace

com.google.auth.ServiceAccountSigner$SigningException: Failed to sign the provided bytes
        at com.google.auth.oauth2.IamUtils.sign(IamUtils.java:87)
        at com.google.auth.oauth2.ComputeEngineCredentials.sign(ComputeEngineCredentials.java:361)
        at com.google.cloud.storage.StorageImpl.signUrl(StorageImpl.java:772)
        at com.google.cloud.storage.Blob.signUrl(Blob.java:822)

Caused by: java.io.IOException: Error code 403 trying to sign provided bytes: The caller does not have permission
        at com.google.auth.oauth2.IamUtils.getSignature(IamUtils.java:125)
        at com.google.auth.oauth2.IamUtils.sign(IamUtils.java:84)
        ... 69 more
```
Any relevant stacktrace here.
```

#### Code snippet

// [START auth_cloud_explicit_compute_engine]
	public Storage authCompute() throws IOException {
		// Explicitly request service account credentials from the compute engine
		// instance.
//GoogleCredentials credentials = ComputeEngineCredentials.create();
		GoogleCredentials credentials = ComputeEngineCredentials.getApplicationDefault();
		Storage storage = StorageOptions.newBuilder().setCredentials(credentials).build().getService();

		System.out.println("Buckets:");
		Page<Bucket> buckets = storage.list();
		for (Bucket bucket : buckets.iterateAll()) {
			System.out.println(bucket.toString());
		}
		return storage;
	}
	// [END auth_cloud_explicit_compute_engine]

Storage storage = authUtil.authCompute();
		Blob blob = storage.get(BlobId.of(bucketName, objectName));
		return blob.signUrl(urlExpirationTime, TimeUnit.MILLISECONDS);

```java
Any relevant code snippet to help reproduce the issue.
```

#### External references such as API reference guides used

- ?

#### Any additional information below

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by subesingh1981** [comment]
Additional information:

My application is deployed on GKE. From there we are trying to download/get signed url a file i.e. stored in GCS.

**Comment by subesingh1981** [comment]
Hello Google Team, Any update please.

**Comment by chingor13** [comment]
The ComputeEngineCredentials uses [IAM sign blob API](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/signBlob) call so the service account being used[ needs to have the `iam.serviceAccounts.signBlob` permission](https://googleapis.dev/java/google-auth-library/latest/com/google/auth/oauth2/ComputeEngineCredentials.html#sign-byte:A-). Depending on your setup, this may be the default service account for the GKE or a workload identity.
