### ISSUE TITLE
ServiceAccountCredentials.fromStream(inputStream, transportFactory) never uses the transportFactory

### ISSUE THREAD

**Issue by tzaenker** [googleapis/google-auth-library-java#557]
Hi,
in a bigger Java-Application I must not change the global Proxy-Settings with System.setProperty ...

So it appears logical to me to use the transportFactory object which can be passed to the ServiceAccountCredentials.fromStream method.

But if I place a debug point into the create function of the create method of this factory it is never called. Sub sequentially also the proxy settings from this transport is never used.

#### Environment details

1. API want to use: Asset API
2. used OS: Windows 7
3. Java version: Java OpenSdk 11.0.8
4. google-auth-library version(s): 0.22.2 and 0.23.0

#### Steps to reproduce

  1. create Own CredentialsProvider
  2. create Own TransportFactory
  3. customize the ListAssetsExample

#### Code example
ListAssetsExample.java
```
 package com.incredible.app;

 // Imports the Google Cloud client library

 import com.google.api.gax.core.CredentialsProvider;
 import com.google.api.gax.core.GoogleCredentialsProvider;
 import com.google.cloud.asset.v1.ProjectName;
 import com.google.cloud.asset.v1p5beta1.Asset;
 import com.google.cloud.asset.v1p5beta1.AssetServiceClient;
 import com.google.cloud.asset.v1p5beta1.AssetServiceClient.ListAssetsPagedResponse;
 import com.google.cloud.asset.v1p5beta1.AssetServiceSettings;
 import com.google.cloud.asset.v1p5beta1.ContentType;
 import com.google.cloud.asset.v1p5beta1.ListAssetsRequest;
 import com.google.common.collect.ImmutableList;

 import java.util.Arrays;

 public class ListAssetsExampleIII {

    public static void main(String... args) {
 /* // With this settings the code would run - but global settings must not be used
        System.setProperty("http.proxyHost", "mycompanyproxy.acme.com");
        System.setProperty("http.proxyPort", "8080");
        System.setProperty("https.proxyHost", "mycompanyproxy.acme.com");
        System.setProperty("https.proxyPort", "8080");
        System.setProperty("http.nonProxyHosts", "*.acme.com");
 */
        try {
            listAssets();
        }
        catch ( Exception e ) {
            e.printStackTrace();
        }
    }

    public static void listAssets() throws Exception {
        // The project id of the asset parent to list.
        String projectId = "THE PROJECT ID";
        // The asset types to list. E.g.,
        // ["storage.googleapis.com/Bucket", "bigquery.googleapis.com/Table"].
        // See full list of supported asset types at
        // https://cloud.google.com/asset-inventory/docs/supported-asset-types.
        String[] assetTypes = {"compute.googleapis.com/Network"};
        // The asset content type to list. E.g., ContentType.CONTENT_TYPE_UNSPECIFIED.
        // See full list of content types at
        // https://cloud.google.com/asset-inventory/docs/reference/rpc/google.cloud.asset.v1p5beta1#contenttype
        ContentType contentType = ContentType.RESOURCE;
        listAssets(projectId, assetTypes, contentType);
    }

    public static void listAssets(String projectId, String[] assetTypes, ContentType contentType)
            throws Exception {
        AssetServiceSettings.Builder assetServiceSettingsBuilder = AssetServiceSettings.newBuilder();

        CredentialsProvider gcp = new CustomizedCredentialsProvider();

        GoogleCredentialsProvider.Builder googleCredentialsProviderBuilder = GoogleCredentialsProvider.newBuilder();

        googleCredentialsProviderBuilder.setScopesToApply(ImmutableList.<String>builder().add("https://www.googleapis.com/auth/cloud-platform").build());
        googleCredentialsProviderBuilder.setJwtEnabledScopes(ImmutableList.copyOf(assetTypes));

        assetServiceSettingsBuilder.setCredentialsProvider(gcp);

        try ( AssetServiceClient client = AssetServiceClient.create(assetServiceSettingsBuilder.build()) ) {
            ProjectName parent = ProjectName.of(projectId);

            // Build initial ListAssetsRequest without setting page token.
            ListAssetsRequest request = ListAssetsRequest.newBuilder()
                    .setParent(parent.toString())
                    .addAllAssetTypes(Arrays.asList(assetTypes))
                    .setContentType(contentType)
                    .build();

            // Repeatedly call ListAssets until page token is empty.
            ListAssetsPagedResponse response = client.listAssets(request);
            System.out.println(response);

            Iterable<Asset> assetList = response.iterateAll();
            for ( Asset asset : assetList ) {
                System.out.println(asset.getName());
            }
        }
    }
 }
```
CustomizedCredentialsProvider.java
```
 package com.incredible.app;

 import com.google.api.gax.core.CredentialsProvider;
 import com.google.auth.Credentials;
 import com.google.auth.http.HttpTransportFactory;
 import com.google.auth.oauth2.GoogleCredentials;
 import com.google.auth.oauth2.ServiceAccountCredentials;

 import java.io.IOException;
 import java.io.InputStream;

 public class CustomizedCredentialsProvider implements CredentialsProvider {

    @Override
    public Credentials getCredentials() throws IOException {
        /* normally here is some crypt stuff but simplified for the showcase */
        InputStream jis = CustomizedCredentialsProvider.class.getResourceAsStream("/com/incredible/app/ServiceAccount.json");
        HttpTransportFactory transportFactory = new CustomizedHttpTransportFacory();
        GoogleCredentials credentials = ServiceAccountCredentials.fromStream(jis, transportFactory);
        return credentials;
    }
 }

```

CustomizedHttpTransportFacory.java
```
 package com.incredible.app;

 import com.google.api.client.http.HttpTransport;
 import com.google.api.client.http.javanet.ConnectionFactory;
 import com.google.api.client.http.javanet.DefaultConnectionFactory;
 import com.google.api.client.http.javanet.NetHttpTransport;
 import com.google.auth.http.HttpTransportFactory;

 import java.net.InetSocketAddress;
 import java.net.Proxy;

 public class CustomizedHttpTransportFacory implements HttpTransportFactory {

    @Override
    public HttpTransport create() {
        /* if you put a breakpoint below here it will never reached */
        NetHttpTransport.Builder transportBuilder = new NetHttpTransport.Builder();
        final Proxy p = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("mycompanyproxy.acme.com", 8080));
        final ConnectionFactory f = new DefaultConnectionFactory(p);
        return transportBuilder.setConnectionFactory(f).build();
    }
 }

```

#### Stack trace
```
> Task :ListAssetsExampleIII.main()
com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 16.533669630s. [buffered_nanos=16536117871, waiting_for_connection]
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:51)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1041)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1215)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.asset.v1p5beta1.AssetServiceClient.listAssets(AssetServiceClient.java:151)
		at com.incredible.app.ListAssetsExampleIII.listAssets(ListAssetsExampleIII.java:75)
		at com.incredible.app.ListAssetsExampleIII.listAssets(ListAssetsExampleIII.java:48)
		at com.incredible.app.ListAssetsExampleIII.main(ListAssetsExampleIII.java:29)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 16.533669630s. [buffered_nanos=16536117871, waiting_for_connection]
	at io.grpc.Status.asRuntimeException(Status.java:533)
	... 13 more
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 16.533669630s. [buffered_nanos=16536117871, waiting_for_connection]

```

Thanks in advance!

**Comment by chingor13** [comment]
The `transportFactory` provided to the `ServiceAccountCredentials.fromStream` is used only by the credentials for its HTTP requests (e.g. token exchanges).

The client that uses the credentials must separately configure proxy settings (it's often a separate transport). In your case of the google-cloud-asset client, you will want to configure the gRPC transport to use a proxy: https://github.com/googleapis/google-cloud-java#grpc-clients
