### ISSUE TITLE
Exception when I use custom tokenServerUri

### ISSUE THREAD

**Issue by kermit-ye** [googleapis/google-auth-library-java#586]
https://xxxx/google/token is a proxy for https://oauth2.googleapis.com/token

code:
```
        PrivateKey privateKey = SecurityUtils.loadPrivateKeyFromKeyStore(SecurityUtils.getPkcs12KeyStore()
                , getClass().getClassLoader().getResourceAsStream("xxxx.p12")
                , "xxx"
                , "xxx"
                , "xxx");
        ServiceAccountCredentials credentials = ServiceAccountCredentials.newBuilder()
                .setTokenServerUri(URI.create("https://xxxx/google/token"))
                .setClientEmail("xxxx")
                .setPrivateKey(privateKey)
                .setScopes(Collections.singleton(ShoppingContentScopes.CONTENT))
                .build();
        credentials.refreshAccessToken();
```

exception: 
```
POST https://xxxx/google/token
{"error":"invalid_grant","error_description":"Invalid JWT: Failed audience check."}
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1116) ~[google-http-client-1.39.0.jar:1.39.0]
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:454) ~[google-auth-library-oauth2-http-0.24.1.jar:na]
	... 5 common frames omitted
```
![image](https://user-images.githubusercontent.com/13169042/109606714-01138500-7b62-11eb-8778-7ec2c9b68cb9.png)
tokenServerUri must be  https://oauth2.googleapis.com/token

**Comment by Neenu1995** [comment]
If you are using a custom proxy, [this example](https://github.com/googleapis/google-auth-library-java#configuring-a-proxy) described in the Google Auth Library documentation will help.
