### ISSUE TITLE
Error parsing token refresh response. Expected value access_token not found.

### ISSUE THREAD

**Issue by WonderLand33** [googleapis/google-auth-library-java#853]
![image](https://user-images.githubusercontent.com/10755158/153599145-d0a777b3-1fcf-483b-8886-53c0ccb9059c.png)

console print:
```
java.io.IOException: Error parsing token refresh response. Expected value access_token not found.
	at com.google.auth.oauth2.OAuth2Utils.validateString(OAuth2Utils.java:112)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:613)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:243)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:240)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:567)
	at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:206)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:156)
	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:1022)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:91)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:404)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at com.kaadas.blend.service.google.impl.GoogleServiceImpl.deviveStatus(GoogleServiceImpl.java:502)
	at com.kaadas.blend.service.device.impl.LockServiceImpl.lambda$deviceStatus$3(LockServiceImpl.java:350)
```
**Why can't get `AccessToken`?
The request response content does not have this field, how to solve it, thank you~**

ENV:
```
jre: openjdk:8-jre-alpine
```
LIB:
```
 <!-- Google Cloud Platform dependencies -->
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-homegraph</artifactId>
            <version>v1-rev20210402-1.32.1</version>
        </dependency>


        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client-gson</artifactId>
            <version>1.32.1</version>
        </dependency>

        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>1.32.1</version>
        </dependency>


        <dependency>
            <groupId>com.google.api</groupId>
            <artifactId>api-common</artifactId>
            <version>2.0.2</version>
        </dependency>

        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client</artifactId>
            <version>1.40.0</version>
        </dependency>


        <dependency>
            <groupId>com.google.auth</groupId>
            <artifactId>google-auth-library-oauth2-http</artifactId>
            <version>1.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-firestore</artifactId>
            <version>2.6.1</version>
            <!--			<exclusions>-->
            <!--				<exclusion>-->
            <!--					<artifactId>netty-buffer</artifactId>-->
            <!--					<groupId>io.netty</groupId>-->
            <!--				</exclusion>-->
            <!--			</exclusions>-->
        </dependency>

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-storage</artifactId>
            <version>2.1.1</version>
        </dependency>
```

**Comment by WonderLand33** [comment]
The problem is solved, and the problem is related.

Causes of problems: `scopes` arguments mistake. 

I think the exception thrown by the SDK is not very clear, it is best to prompt 401 no permission or something.

Cheers!
