### ISSUE TITLE
ClassCastException in ImpersonatedCredentials.createScoped

### ISSUE THREAD

**Issue by spkrka** [googleapis/google-auth-library-java#887]
Stacktrace:
```
    Caused by: java.lang.ClassCastException: class com.google.common.collect.SingletonImmutableSet cannot be cast to class java.util.List (com.google.common.collect.Single>
        at com.google.auth.oauth2.ImpersonatedCredentials.createScoped(ImpersonatedCredentials.java:367)
        at com.google.cloud.ServiceOptions.getScopedCredentials(ServiceOptions.java:596)
        at com.google.cloud.http.HttpTransportOptions.getHttpRequestInitializer(HttpTransportOptions.java:145)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.<init>(HttpStorageRpc.java:111)
        at com.google.cloud.storage.StorageOptions$DefaultStorageRpcFactory.create(StorageOptions.java:55)
        at com.google.cloud.storage.StorageOptions$DefaultStorageRpcFactory.create(StorageOptions.java:49)
        at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:560)
        at com.google.cloud.storage.StorageOptions.getStorageRpcV1(StorageOptions.java:121)
        at com.google.cloud.storage.StorageImpl.<init>(StorageImpl.java:111)
        at com.google.cloud.storage.StorageOptions$DefaultStorageFactory.create(StorageOptions.java:45)
        at com.google.cloud.storage.StorageOptions$DefaultStorageFactory.create(StorageOptions.java:39)
        at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:540)

```

**Comment by TimurSadykov** [comment]
this is being addressed by #732, it is ready to checkin.
