### ISSUE TITLE
Caused by: java.io.EOFException: SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by jcdesignweb** [googleapis/google-auth-library-java#987]
Hi Guys! I hope you can help with this issue, it is very important to solve as soon as I can because its and Prod error.

This works fine in develop and staging environments. This issue happends sometimes in prod, I am using this library to get the Access Token to use it for FCM Push notifications and sometimes when I want to get the new Access token the server returns this: 

`**java.io.IOException: Error getting access token for service account: Remote host closed connection during handshake, iss: firebase-adminsdk-xxx@xxxx.gserviceaccount.com**
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:569)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:257)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:254)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:580)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:180)
	at com.simplytapp.common.soa.gcm.fcm.FcmAuthManager.subIntervalAccessToken(FcmAuthManager.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	
	
**Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake**
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:564)
	... 14 more
	
	
**Caused by: java.io.EOFException: SSL peer shut down incorrectly**
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	... 26 more
`
 
#### Environment details

- OS: Linux
- Java version: 1.8
- google-auth-library-java version(s): 1.8.0

I would like know the cause of this, because usually works fine but sometimes it does not.

TIA !

**Comment by TimurSadykov** [comment]
Hey, sorry for late reply, have you found the solution? Is there a chance you use TLSv1.0? This error seem to be common for that version

**Comment by westarle** [comment]
Please reopen if you are still experiencing this error and need help.
